app_name: company-accounts.web.ch.gov.uk
group: web
weight: 910
routes:
   1: ^/company/(.*)/small-full/
   2: ^/company/(.*)/transaction/(.*)/company-accounts/(.*)/small-full/
   3: ^/company/(.*)/corporation-tax
   4: ^/company/(.*)/dormant/
   5: ^/company/(.*)/micro-entity/
   6: ^/company/(.*)/select-account-type
   7: ^/company/(.*)/dormant/
   8: ^/accounts/criteria
   9: ^/accounts/alternative-filing-options
   10: ^/accounts/corporation-tax
   11: ^/accounts/select-account-type
   12: ^/accounts/full-accounts-criteria
   13: ^/company/(.*)/cic/ 
