app_name: company-accounts.web.ch.gov.uk
group: web
weight: 910
routes:
   1: /company/(.*)/small-full/
   2: /company/(.*)/transaction/(.*)/company-accounts/(.*)/small-full/
   3: /company/(.*)/corporation-tax
