app_name: company-accounts.web.ch.gov.uk
group: web
weight: 910
routes:
   1: ^/company/(.*)/small-full/
   2: ^/company/(.*)/transaction/(.*)/company-accounts/(.*)/small-full/
   3: ^/company/(.*)/corporation-tax
   4: ^/company/(.*)/dormant/
   5: ^/company/(.*)/micro-entity/
   6: ^/company/(.*)/select-account-type
   7: ^/company/(.*)/dormant/
   8: ^/accounts/criteria
   9: ^/accounts/cic/full-accounts-criteria
   10: ^/accounts/cic/criteria
   11: ^/accounts/cic/cant-file-online-yet
   12: ^/accounts/cic/cics-file-paper
   13: ^/accounts/alternative-filing-options
   14: ^/accounts/corporation-tax
   15: ^/accounts/select-account-type
   16: ^/accounts/full-accounts-criteria
   17: ^/accounts/company/(.*)/details
   18: ^/company/(.*)/cic/
   19: ^/company/(.*)/transaction/(.*)/company-accounts/(.*)/resume
   20: ^/company/(.*)/transaction/(.*)/company-accounts/(.*)/cic/